### ISSUE TITLE
Snap not running after installation, NVIDIA

### ISSUE THREAD

**Issue by JoshDesmond** [Imberflur/veloren-snap#8] opened 2022-06-28 02:22 UTC
Terminal output: https://paste.ubuntu.com/p/DkSFtzwzTM/
Operating System: Ubuntu 20.04.4 LTS, 64bit
Graphics Card: 
```
viridian@trololubuntu:~$ sudo lshw -C video
  *-display                 
       description: VGA compatible controller
       product: GP106 [GeForce GTX 1060 6GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:26:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:57 memory:f6000000-f6ffffff memory:e0000000-efffffff memory:f0000000-f1ffffff ioport:f000(size=128) memory:c0000-dffff
```
Wayland or X11: `X11`
vulkaninfo output: https://paste.ubuntu.com/p/Ggb3CBfKfP/

I am not going to bother trying an alternative installation. I am not all that interested in installing/running the game, but I figured I would pass along the info I had to y'all. Perhaps I will give it another try someday in the future.

**Comment by Imberflur** [comment] 2022-09-18 19:22
Thanks for the info! I'm closing this since there is not much I can do to debug this. If anyone has a similar problem please open a new issue and we can hopefully work out what the cause is!

**Closed by Imberflur** 2022-09-18 19:22 UTC
